include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_constructors_in_immutables
    - avoid_print
    - use_key_in_widget_constructors
    - avoid_unnecessary_containers
    - prefer_single_quotes
